{
 "title": "Linux node / network",
 "tags": [ "linux-node-integration" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_uname_info{job=~\"integrations/(node_exporter|unix)\"}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network interfaces overview",
   "type": "table",
   "description": "Network interfaces overview.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_network_up{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "node_network_carrier{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8",
     "legendFormat": "{{ device }} transmitted"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8",
     "legendFormat": "{{ device }} received"
    },
    {
     "expr": "node_arp_entries{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "node_network_mtu_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "node_network_speed_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"} * 8"
    },
    {
     "expr": "node_network_transmit_queue_length{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "node_network_info{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "description": "Network traffic (bits per sec) measures data transmitted and received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8\n# only show interfaces that had traffic change at least once during selected dashboard interval:\nand\nincrease(\n    node_network_receive_bytes_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__range]\n    ) > 0\n",
     "legendFormat": "{{ device }} received"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8\n# only show interfaces that had traffic change at least once during selected dashboard interval:\nand\nincrease(\n    node_network_transmit_bytes_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__range]\n    ) > 0\n",
     "legendFormat": "{{ device }} transmitted"
    }
   ]
  },
  {
   "title": "Network interfaces carrier status",
   "type": "status-history",
   "description": "Network interfaces carrier status",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "node_network_carrier{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "timeseries",
   "description": "Network errors refer to issues that occur during the transmission of data across a network. \n\nThese errors can result from various factors, including physical issues, jitter, collisions, noise and interference.\n\nMonitoring network errors is essential for diagnosing and resolving issues, as they can indicate problems with network hardware or environmental factors affecting network quality.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ device }} errors received"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ device }} errors transmitted"
    }
   ]
  },
  {
   "title": "Dropped packets",
   "type": "timeseries",
   "description": "Dropped packets occur when data packets traveling through a network are intentionally discarded or lost due to congestion, resource limitations, or network configuration issues. \n\nCommon causes include network congestion, buffer overflows, QoS settings, and network errors, as corrupted or incomplete packets may be discarded by receiving devices.\n\nDropped packets can impact network performance and lead to issues such as degraded voice or video quality in real-time applications.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ device }} received dropped"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ device }} transmitted dropped"
    }
   ]
  },
  {
   "title": "Network packets",
   "type": "timeseries",
   "description": "Network packet count tracks the number of data packets transmitted and received over a network connection, providing insight into network activity and performance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ device }} received"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ device }} transmitted"
    }
   ]
  },
  {
   "title": "Multicast packets",
   "type": "timeseries",
   "description": "Multicast packets received and transmitted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_multicast_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ device }} received"
    },
    {
     "expr": "irate(node_network_transmit_multicast_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ device }} transmitted"
    }
   ]
  },
  {
   "title": "Network FIFO",
   "type": "timeseries",
   "description": "Network FIFO (First-In, First-Out) refers to a buffer used by the network stack to store packets in a queue.\nIt is a mechanism used to manage network traffic and ensure that packets are delivered to their destination in the order they were received.\nPackets are stored in the FIFO buffer until they can be transmitted or processed further.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_fifo_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ device }} received"
    },
    {
     "expr": "irate(node_network_transmit_fifo_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ device }} transmitted"
    }
   ]
  },
  {
   "title": "Compressed packets",
   "type": "timeseries",
   "description": "- Compressed received: \nNumber of correctly received compressed packets. This counters is only meaningful for interfaces which support packet compression (e.g. CSLIP, PPP).\n\n- Compressed transmitted:\nNumber of transmitted compressed packets. This counters is only meaningful for interfaces which support packet compression (e.g. CSLIP, PPP).\n\nhttps://docs.kernel.org/networking/statistics.html\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_compressed_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ device }} received"
    },
    {
     "expr": "irate(node_network_transmit_compressed_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ device }} transmitted"
    }
   ]
  },
  {
   "title": "NF conntrack",
   "type": "timeseries",
   "description": "NF Conntrack is a component of the Linux kernel's netfilter framework that provides stateful packet inspection to track and manage network connections,\nenforce firewall rules, perform NAT, and manage network address/port translation.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "NF conntrack entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "NF conntrack limits"
    }
   ]
  },
  {
   "title": "Softnet packets",
   "type": "timeseries",
   "description": "Softnet packets are received by the network and queued for processing by the kernel's networking stack.\nSoftnet packets are usually generated by network traffic that is directed to the local host, and they are typically processed by the kernel's networking subsystem before being passed on to the relevant application. \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_softnet_processed_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }} processed"
    },
    {
     "expr": "irate(node_softnet_dropped_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }} dropped"
    }
   ]
  },
  {
   "title": "Softnet out of quota",
   "type": "timeseries",
   "description": "\"Softnet out of quota\" is a network-related metric in Linux that measures the number of times the kernel's softirq processing was unable to handle incoming network traffic due to insufficient softirq processing capacity.\nThis means that the kernel has reached its processing capacity limit for incoming packets, and any additional packets will be dropped or deferred.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_softnet_times_squeezed_total{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }} out of quota"
    }
   ]
  },
  { "title": "Network sockets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Sockets in use",
   "type": "timeseries",
   "description": "Number of sockets currently in use.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv4 sockets in use"
    }
   ]
  },
  {
   "title": "Sockets TCP",
   "type": "timeseries",
   "description": "TCP sockets are used for establishing and managing network connections between two endpoints over the TCP/IP protocol.\n\nOrphan sockets: If a process terminates unexpectedly or is terminated without closing its sockets properly, the sockets may become orphaned.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "node_sockstat_TCP_inuse{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv4 in use"
    },
    {
     "expr": "node_sockstat_TCP6_inuse{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv6 in use"
    },
    {
     "expr": "node_sockstat_TCP_orphan{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Orphan sockets"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Time wait"
    }
   ]
  },
  {
   "title": "Sockets UDP",
   "type": "timeseries",
   "description": "UDP (User Datagram Protocol) and UDPlite (UDP-Lite) sockets are used for transmitting and receiving data over the UDP and UDPlite protocols, respectively.\nBoth UDP and UDPlite are connectionless protocols that do not provide a reliable data delivery mechanism.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "node_sockstat_UDPLITE_inuse{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv4 UDPLITE in use"
    },
    {
     "expr": "node_sockstat_UDP_inuse{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv4 UDP in use"
    },
    {
     "expr": "node_sockstat_UDPLITE6_inuse{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv6 UDPLITE in use"
    },
    {
     "expr": "node_sockstat_UDP6_inuse{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv6 UDP in use"
    }
   ]
  },
  {
   "title": "Sockets memory",
   "type": "timeseries",
   "description": "Memory currently in use for sockets.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "node_sockstat_TCP_mem{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory pages allocated for TCP sockets"
    },
    {
     "expr": "node_sockstat_UDP_mem{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory pages allocated for UDP sockets"
    },
    {
     "expr": "node_sockstat_TCP_mem_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory bytes allocated for TCP sockets"
    },
    {
     "expr": "node_sockstat_UDP_mem_bytes{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory bytes allocated for UDP sockets"
    }
   ]
  },
  {
   "title": "Sockets other",
   "type": "timeseries",
   "description": "FRAG (IP fragment) sockets: Used to receive and process fragmented IP packets. FRAG sockets are useful in network monitoring and analysis.\n\nRAW sockets: Allow applications to send and receive raw IP packets directly without the need for a transport protocol like TCP or UDP.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "node_sockstat_FRAG_inuse{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv4 Frag sockets in use"
    },
    {
     "expr": "node_sockstat_FRAG6_inuse{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv6 Frag sockets in use"
    },
    {
     "expr": "node_sockstat_RAW_inuse{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv4 Raw sockets in use"
    },
    {
     "expr": "node_sockstat_RAW6_inuse{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv6 Raw sockets in use"
    }
   ]
  },
  { "title": "Network netstat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "IP octets",
   "type": "timeseries",
   "description": "Rate of IP octets received and transmitted.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "oct/s" } },
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InOctets{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Octets received"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutOctets{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Octets transmitted"
    }
   ]
  },
  {
   "title": "TCP segments",
   "type": "timeseries",
   "description": "Rate of TCP segments received and transmitted.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_InSegs{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP received"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP transmitted"
    }
   ]
  },
  {
   "title": "TCP errors rate",
   "type": "timeseries",
   "description": "Rate of TCP errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP overflow"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP ListenDrops - SYNs to LISTEN sockets ignored"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP SYN rentransmits"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP retransmitted segments, containing one or more previously transmitted octets"
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP received with errors"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutRsts{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP segments sent with RST flag"
    }
   ]
  },
  {
   "title": "UDP datagrams",
   "type": "timeseries",
   "description": "Rate of UDP datagrams received and transmitted.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "dat/s" } },
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP received"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP transmitted"
    },
    {
     "expr": "irate(node_netstat_Udp6_InDatagrams{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP6 received"
    },
    {
     "expr": "irate(node_netstat_Udp6_OutDatagrams{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP6 transmitted"
    }
   ]
  },
  {
   "title": "UDP errors rate",
   "type": "timeseries",
   "description": "Rate of UDP errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "irate(node_netstat_UdpLite_InErrors{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDPLite InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_InErrors{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp6_InErrors{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP6 InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP NoPorts"
    },
    {
     "expr": "irate(node_netstat_Udp6_NoPorts{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP6 NoPorts"
    },
    {
     "expr": "irate(node_netstat_Udp_RcvbufErrors{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP receive buffer errors"
    },
    {
     "expr": "irate(node_netstat_Udp6_RcvbufErrors{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP6 receive buffer errors"
    },
    {
     "expr": "irate(node_netstat_Udp_SndbufErrors{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP transmit buffer errors"
    },
    {
     "expr": "irate(node_netstat_Udp6_SndbufErrors{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP6 transmit buffer errors"
    }
   ]
  },
  {
   "title": "ICMP messages",
   "type": "timeseries",
   "description": "Rate of ICMP messages, like 'ping', received and transmitted.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InMsgs{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ICMP received"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutMsgs{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ICMP transmitted"
    },
    {
     "expr": "irate(node_netstat_Icmp6_InMsgs{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ICMP6 received"
    },
    {
     "expr": "irate(node_netstat_Icmp6_OutMsgs{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ICMP6 transmitted"
    }
   ]
  },
  {
   "title": "ICMP errors rate",
   "type": "timeseries",
   "description": "Rate of ICMP messages received and transmitted with errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InErrors{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ICMP6 errors"
    },
    {
     "expr": "irate(node_netstat_Icmp6_InErrors{job=~\"integrations/(node_exporter|unix)\",cluster=~\"$cluster\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ICMP6 errors"
    }
   ]
  }
 ]
}